export enum EKnownHeaders {
  ACCEPT = 'Accept',
  ACCEPT_DATETIME = 'Accept-Datetime',
  ACCEPT_LANGUAGE = 'Accept-Language',
  ACCEPT_ENCODING = 'Accept-Encoding',
  AUTHORIZATION = 'Authorization',
  CACHE_CONTROL = 'Cache-Control',
  CONTENT_MD5 = 'Content-MD5',
  CONTENT_TYPE = 'Content-Type',
  CONNECTION = 'Connection',
  ENABLE_TRACING = 'Enable-Tracing',
  FORWARDED = 'Forwarded',
  FROM = 'From',
  HOST = 'Host',
  HTTP2_SETTINGS = 'HTTP2-Settings',
  IF_MATCH = 'If-Match',
  IF_MODIFIED_SINCE = 'If-Modified-Since',
  IF_NONE_MATCH = 'If-None-Match',
  IF_RANGE = 'If-Range',
  IF_UNMODIFIED_SINCE = 'If-Unmodified-Since',
  MAX_FORWARDS = 'Max-Forwards',
  ORIGIN = 'Origin',
  PRAGMA = 'Pragma',
  REFERER = 'Referer',
  RANGE = 'Range',
  USER_AGENT = 'User-Agent',
  WARNING = 'Warning'
}

export const KNOWN_HEADERS = {
  ACCEPT: EKnownHeaders.ACCEPT,
  ACCEPT_DATETIME: EKnownHeaders.ACCEPT_DATETIME,
  ACCEPT_LANGUAGE: EKnownHeaders.ACCEPT_LANGUAGE,
  ACCEPT_ENCODING: EKnownHeaders.ACCEPT_ENCODING,
  AUTHORIZATION: EKnownHeaders.AUTHORIZATION,
  CACHE_CONTROL: EKnownHeaders.CACHE_CONTROL,
  CONTENT_MD5: EKnownHeaders.CONTENT_MD5,
  CONTENT_TYPE: EKnownHeaders.CONTENT_TYPE,
  CONNECTION: EKnownHeaders.CONNECTION,
  ENABLE_TRACING: EKnownHeaders.ENABLE_TRACING,
  FORWARDED: EKnownHeaders.FORWARDED,
  FROM: EKnownHeaders.FROM,
  HOST: EKnownHeaders.HOST,
  HTTP2_SETTINGS: EKnownHeaders.HTTP2_SETTINGS,
  IF_MATCH: EKnownHeaders.IF_MATCH,
  IF_MODIFIED_SINCE: EKnownHeaders.IF_MODIFIED_SINCE,
  IF_NONE_MATCH: EKnownHeaders.IF_NONE_MATCH,
  IF_RANGE: EKnownHeaders.IF_RANGE,
  IF_UNMODIFIED_SINCE: EKnownHeaders.IF_UNMODIFIED_SINCE,
  MAX_FORWARDS: EKnownHeaders.MAX_FORWARDS,
  ORIGIN: EKnownHeaders.ORIGIN,
  PRAGMA: EKnownHeaders.PRAGMA,
  REFERER: EKnownHeaders.REFERER,
  RANGE: EKnownHeaders.RANGE,
  USER_AGENT: EKnownHeaders.USER_AGENT,
  WARNING: EKnownHeaders.WARNING
};
